import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";
import Header from "@/components/screen/layout/header/Header";
import Footer from "@/components/screen/layout/footer/Footer";
import Providers from "@/providers/Providers";



const onest = Onest({
    weight: ['400', '500', '600', '700'],
    subsets: ['latin', 'cyrillic-ext'],
    display: 'swap',
    style: ['normal'],
    variable: '--font-onest'
}) 

export const metadata: Metadata = {
  title: "Кейс | Smart Leads",
  description: "Generated by our company",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${onest.variable} antialiased`} >
          <Providers>
            <div className="text-sec-black">
              <Header/>
            </div>
            <main className="bg-white">
              {children}
            </main>
            <Footer/>
          </Providers>
        <div id="modal"></div>
      </body>
    </html>
  );
}
